import EventKit
import AppKit
import Foundation
import SwiftUI
import Testing
@testable import MouthyKit
@testable import MouthyNotch
import MouthyCore

@Test func lyricsParseTimestampsAndSkipJunk() {
    let lines = LyricsClient.parse("[00:12.50] First line\n[01:02.00]Second\nnot a lyric\n[ar:Someone]\n[02:00.00] ")
    #expect(lines.map(\.time) == [12.5, 62, 120])
    #expect(lines.map(\.text) == ["First line", "Second", ""])
}

@Test func usageCountsClaudeOncePerMessageAndCodexWithoutCacheReads() throws {
    let now = Date()
    let iso = ISO8601DateFormatter()
    iso.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
    let folder = FileManager.default.temporaryDirectory.appendingPathComponent("mouthy-usage-\(UUID().uuidString)")
    try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
    defer { try? FileManager.default.removeItem(at: folder) }
    let recent = iso.string(from: now.addingTimeInterval(-3600)), old = iso.string(from: now.addingTimeInterval(-6 * 86400))
    let claude = """
    {"type":"assistant","requestId":"r1","timestamp":"\(recent)","message":{"id":"m1","content":"secret words","usage":{"input_tokens":10,"output_tokens":90,"cache_creation_input_tokens":100,"cache_read_input_tokens":5000}}}
    {"type":"assistant","requestId":"r1","timestamp":"\(recent)","message":{"id":"m1","usage":{"input_tokens":10,"output_tokens":90,"cache_creation_input_tokens":100,"cache_read_input_tokens":5000}}}
    {"type":"assistant","requestId":"r2","timestamp":"\(old)","message":{"id":"m2","usage":{"input_tokens":1,"output_tokens":1}}}
    {"type":"user","message":{"content":"no usage here"}}
    """
    let file = folder.appendingPathComponent("a.jsonl")
    try claude.write(to: file, atomically: true, encoding: .utf8)
    var samples: [UsageScanner.Sample] = []
    var seen = Set<String>()
    UsageScanner.forEachLine(file, containing: "\"usage\"") { object in
        guard let message = object["message"] as? [String: Any], let usage = message["usage"] as? [String: Any],
              let date = UsageScanner.parseDate(object["timestamp"]),
              seen.insert((message["id"] as? String ?? "") + (object["requestId"] as? String ?? "")).inserted else { return }
        samples.append(.init(date: date, tokens: ["input_tokens", "output_tokens", "cache_creation_input_tokens"].reduce(0) { $0 + ((usage[$1] as? Int) ?? 0) }))
    }
    let summary = UsageScanner.summarize("Claude Code", samples, limits: [], now: now)
    #expect(summary.fiveHours == 200 && summary.week == 202)
    #expect(summary.hourly.reduce(0, +) == 200)
    #expect(UsageScanner.recentFiles(under: folder, now: now) == [file].map { $0.resolvingSymlinksInPath() } || UsageScanner.recentFiles(under: folder, now: now).count == 1)
}

@MainActor @Test func clipboardSkipsConcealedTransientAndGeneratedItems() {
    for marker in ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"] {
        #expect(ClipboardTab.shouldSkip(types: ["public.utf8-plain-text", marker]))
    }
    #expect(!ClipboardTab.shouldSkip(types: ["public.utf8-plain-text"]))
    #expect(ClipboardTab.pollInterval == 1.5 && ClipboardTab.pollTolerance == 1.0)
}

@Test func usageReadsOnlyNewCompleteLines() throws {
    let file = FileManager.default.temporaryDirectory.appendingPathComponent("mouthy-lines-\(UUID().uuidString).jsonl")
    defer { try? FileManager.default.removeItem(at: file) }
    try "{\"usage\":1}\n{\"usage\":2}\n{\"usa".write(to: file, atomically: true, encoding: .utf8)
    var seen: [Int] = []
    let first = UsageScanner.forEachLine(file, containing: "usage") { seen.append($0["usage"] as? Int ?? 0) }
    #expect(seen == [1, 2])
    let handle = try FileHandle(forWritingTo: file); try handle.seekToEnd()
    try handle.write(contentsOf: Data("ge\":3}\n".utf8)); try handle.close()
    let second = UsageScanner.forEachLine(file, from: first, containing: "usage") { seen.append($0["usage"] as? Int ?? 0) }
    #expect(seen == [1, 2, 3] && second > first)
}

/// Lines at and over `longest`: a long line that holds the marker still
/// counts, even with the marker split across two reads; a long line without it is skipped.
@Test func usageKeepsLongLinesThatHoldTheMarker() throws {
    let file = FileManager.default.temporaryDirectory.appendingPathComponent("mouthy-long-\(UUID().uuidString).jsonl")
    defer { try? FileManager.default.removeItem(at: file) }
    let longest = 64
    func padded(_ usage: Int, to length: Int) -> String {
        let head = #"{"usage":\#(usage),"p":""#
        return head + String(repeating: "x", count: length - head.utf8.count - 2) + #""}"#
    }
    let atLimit = padded(1, to: longest), overLimit = padded(2, to: longest + 1)
    let noMarker = #"{"p":""# + String(repeating: "y", count: 20_000) + #""}"#
    // "usage" starts two bytes before the first 32 KB read ends.
    let offset = [atLimit, overLimit, noMarker].reduce(0) { $0 + $1.utf8.count + 1 }
    let split = #"{"p":""# + String(repeating: "z", count: (32 << 10) - 2 - offset - 9) + #"","usage":4}"#
    try [atLimit, overLimit, noMarker, split, #"{"usage":5}"#].map { $0 + "\n" }.joined().write(to: file, atomically: true, encoding: .utf8)
    #expect(atLimit.utf8.count == longest && overLimit.utf8.count == longest + 1)
    var seen: [Int] = []
    let end = UsageScanner.forEachLine(file, containing: "usage", longest: longest) { seen.append($0["usage"] as? Int ?? 0) }
    #expect(seen == [1, 2, 4, 5], "\(seen)")
    #expect(end == (try FileManager.default.attributesOfItem(atPath: file.path)[.size] as? Int))
}

/// MOUTHY_TEST_USAGE=1 times a scan of this Mac's real logs (token counts only) and a second, incremental one.
@Test func usageScanOfRealLogsIsBounded() {
    guard ProcessInfo.processInfo.environment["MOUTHY_TEST_USAGE"] == "1" else { return }
    let clock = ContinuousClock()
    let first = clock.measure { _ = UsageScanner.lock.withLock { UsageScanner.codex(now: Date()) } }
    let second = clock.measure { _ = UsageScanner.lock.withLock { UsageScanner.codex(now: Date()) } }
    print("usage scan first \(first), second \(second)")
    #expect(second < .seconds(1))
}

/// MOUTHY_TEST_NETWORK=1: real Open-Meteo geocoding and LRCLIB lyrics (public, keyless services).
@MainActor @Test func notchNetworkServicesAnswer() async throws {
    guard ProcessInfo.processInfo.environment["MOUTHY_TEST_NETWORK"] == "1" else { return }
    let place = try #require(await WeatherTab.geocode("Paris, France"))
    #expect(place.country_code == "FR" && abs(place.latitude - 48.9) < 0.2)
    let spaced = try #require(await WeatherTab.geocode("Paris France"))
    #expect(spaced.country_code == "FR")
    let lyrics = await LyricsClient.fetch(.init(title: "Bohemian Rhapsody", artist: "Queen", album: "A Night at the Opera", duration: 355, player: "Music"))
    #expect(lyrics.synced.count > 20)
}

@Test func shortcutsCommandLists() throws {
    guard ProcessInfo.processInfo.environment["MOUTHY_TEST_NETWORK"] == "1" else { return }
    _ = try ShortcutsTab.shortcuts(["list"])   // the command runs; the library may be empty
}

@Test func calendarFindsVideoCallLinks() {
    #expect(CalendarTab.joinLink(in: [nil, "Room 4", "Join: https://us02web.zoom.us/j/8123456789?pwd=abc."])?.host == "us02web.zoom.us")
    #expect(CalendarTab.joinLink(in: ["https://meet.google.com/abc-defg-hij"])?.absoluteString == "https://meet.google.com/abc-defg-hij")
    #expect(CalendarTab.joinLink(in: ["<https://teams.microsoft.com/l/meetup-join/19%3ameeting>"]) != nil)
    #expect(CalendarTab.joinLink(in: ["https://example.com/agenda", "Lunch"]) == nil)
}

@MainActor @Test func hubReordersAndPagesTabs() {
    let hub = NotchHub.shared
    let ids = ["page.a", "page.b", "page.c"]
    ids.map { SampleTab(id: $0) }.forEach(hub.register)
    defer { ids.forEach(hub.unregister) }
    hub.reorder(["page.c", "page.a", "missing"])
    let mine = hub.tabIDs.filter(ids.contains)
    #expect(mine == ["page.c", "page.a", "page.b"])
    hub.selectedID = hub.tabIDs.last
    hub.selectAdjacent(1)
    #expect(hub.selectedID == hub.tabIDs.first)
    hub.selectAdjacent(-1)
    #expect(hub.selectedID == hub.tabIDs.last)
}

@MainActor @Test func artworkLookupAnswers() async {
    guard ProcessInfo.processInfo.environment["MOUTHY_TEST_NETWORK"] == "1" else { return }
    let image = await ArtworkClient.fetch(.init(title: "Bohemian Rhapsody", artist: "Queen", album: "", duration: 355, player: "Music"))
    #expect((image?.size.width ?? 0) >= 100)
}

// MARK: Logic

@Test func coolArtGlowsWarm() {
    // Blue album art (hue 0.6) glows mic-glow amber at 0.6 saturation; warm art keeps its hue, a little richer.
    let blue = ambientHSB(hue: 0.6, saturation: 0.8, brightness: 0.4)
    #expect(abs(blue.hue - glowHue) < 0.001 && blue.saturation == 0.6 && blue.brightness >= 0.6)
    let teal = ambientHSB(hue: 0.5, saturation: 0.5, brightness: 0.9)
    #expect(abs(teal.hue - glowHue) < 0.001)
    let violet = ambientHSB(hue: 0.8, saturation: 0.5, brightness: 0.9)
    #expect(abs(violet.hue - glowHue) < 0.001)
    let red = ambientHSB(hue: 0.02, saturation: 0.5, brightness: 0.3)
    #expect(red.hue == 0.02 && abs(red.saturation - 0.6) < 0.001 && red.brightness == 0.55)
    let magenta = ambientHSB(hue: 0.9, saturation: 0.5, brightness: 0.7)
    #expect(magenta.hue == 0.9)
}

@MainActor @Test func calendarColoursStayWarm() {
    let blue = CGColor(srgbRed: 0.1, green: 0.4, blue: 0.95, alpha: 1)
    let warm = NSColor(CalendarTab.warm(blue)).usingColorSpace(.sRGB)!
    #expect(abs(warm.hueComponent - glowHue) < 0.01)
    #expect(MouthyTheme.hexValue(CalendarTab.warm(nil)) == 0xE08A2E)
}

@MainActor @Test func timerShowsTheSelectedLengthBeforeStarting() {
    let timers = TimersTab.shared
    timers.stop()
    timers.countdownMinutes = 12
    timers.selected = .countdown
    #expect(timers.minutes(for: timers.selected) == 12)
    timers.start(.rest)
    defer { timers.stop() }
    #expect(timers.selected == .rest && timers.running?.length == TimeInterval(timers.restMinutes * 60))
    #expect(timers.badge?.tint == nil, "one badge style: the hub's glow dot")
    #expect(timers.badge?.isLive == true, "a running timer keeps its dot on the compact rail")
}

@MainActor @Test func voiceTabFallsBackToHistoryAndOffersPasteLast() {
    let saved = [MouthyCore.Transcript(raw: "from history", text: "from history", duration: 2, source: "Notes", mode: "Natural")]
    #expect(VoiceTabView.recentTexts(session: [], history: saved) == ["from history"])
    #expect(VoiceTabView.recentTexts(session: ["this session"], history: saved) == ["this session"])
    #expect(VoiceTabView.recentTexts(session: (0..<12).map(String.init), history: []).count == 8)
    #expect(!VoiceTabView.canPasteLast(output: "", history: []))
    #expect(VoiceTabView.canPasteLast(output: "last", history: []))
    #expect(VoiceTabView.canPasteLast(output: "", history: saved))
}

/// Counts every HTTP request URLSession.shared tries, and fails it without touching the network.
final class RequestCounter: URLProtocol, @unchecked Sendable {
    nonisolated(unsafe) static var count = 0
    static let lock = NSLock()
    override class func canInit(with request: URLRequest) -> Bool {
        guard request.url?.scheme?.hasPrefix("http") == true else { return false }
        lock.withLock { count += 1 }
        return true
    }
    override class func canonicalRequest(for request: URLRequest) -> URLRequest { request }
    override func startLoading() { client?.urlProtocol(self, didFailWithError: URLError(.notConnectedToInternet)) }
    override func stopLoading() {}
}

@MainActor @Test func localOnlyModeStopsEveryNotchRequest() async {
    let original = MouthyTabs.networkAllowed
    URLProtocol.registerClass(RequestCounter.self)
    defer { MouthyTabs.networkAllowed = original; URLProtocol.unregisterClass(RequestCounter.self) }
    let track = MusicTab.Track(title: "Song", artist: "Artist", album: "", duration: 200, player: "Music")
    let place = WeatherTab.Place(name: "Paris", latitude: 48.9, longitude: 2.3, fahrenheit: true)

    MouthyTabs.networkAllowed = { false }
    RequestCounter.lock.withLock { RequestCounter.count = 0 }
    let art = await ArtworkClient.fetch(track)
    let lyrics = await LyricsClient.fetch(track)
    let forecast = await WeatherTab.forecast(for: place)
    let city = await WeatherTab.geocode("Paris")
    #expect(art == nil && lyrics.synced.isEmpty && lyrics.plain == nil && forecast == nil && city == nil)
    #expect(RequestCounter.lock.withLock { RequestCounter.count } == 0)

    // The same calls with the network allowed do try (and fail here), so the check above means something.
    MouthyTabs.networkAllowed = { true }
    _ = await WeatherTab.forecast(for: place)
    #expect(RequestCounter.lock.withLock { RequestCounter.count } > 0)
}

// MARK: Renders

/// The voice tab drawn from a scratch model, so renders never show this Mac's real dictation history.
@MainActor final class PreviewVoiceTab: NotchTab {
    let id = VoiceTab.shared.id
    let title = VoiceTab.shared.title
    let symbolName = VoiceTab.shared.symbolName
    let model: AppModel
    let recent = RecentResults()
    init(model: AppModel) {
        self.model = model
        ["Ship the notch hub tonight.", "Book the dentist for Thursday at nine.", "Thanks, that works for me."].reversed().forEach(recent.add)
    }
    func makeBody() -> AnyView { AnyView(VoiceTabView(model: model, recent: recent)) }
}

/// MOUTHY_RENDER_DIR=<dir>: PNG of each Mouthy tab inside the open notch, plus loading and Local Only states.
@MainActor @Test func mouthyTabsRenderForVisualReview() throws {
    guard ProcessInfo.processInfo.environment["MOUTHY_RENDER_DIR"] != nil else { return }
    let original = MouthyTabs.networkAllowed
    let originalFolder = MouthyTabs.storageFolder
    MouthyTabs.networkAllowed = { false }
    defer { MouthyTabs.networkAllowed = original; MouthyTabs.storageFolder = originalFolder }
    let scratch = FileManager.default.temporaryDirectory.appendingPathComponent("mouthy-render-\(UUID().uuidString)")
    defer { try? FileManager.default.removeItem(at: scratch) }
    MouthyTabs.storageFolder = scratch.appendingPathComponent("Notch")
    let model = AppModel(store: LocalStore(directory: scratch), enablesHotkey: false)
    model.stats.record(text: String(repeating: "word ", count: 1284), seconds: 640)
    model.output = "Ship the notch hub tonight."

    Mascot.install()
    let hub = NotchHub()
    hub.register(PreviewVoiceTab(model: model))
    MouthyTabs.registerAll(in: hub)
    hub.headerTrailing = { AnyView(HeaderTabStatus(hub: hub)) }
    NotesTab.shared.todos = [.init(text: "Ship the notch hub"), .init(text: "Record the demo video"), .init(text: "Order more filament", done: true)]
    NotesTab.shared.note = "Host apps get the Agents tab."
    MusicTab.shared.lyricsEnabled = false
    MusicTab.shared.update(["Name": "One Day (Vandaag) - Radio Edit", "Artist": "Bakermat", "Album": "One Day", "Player State": "Playing", "Duration": 203000, "Playback Position": 61.0], player: "Spotify")
    ClipboardTab.shared.showForPreview(["Meet at the north entrance at 6", "https://mouthy.dev", "Two microphones. No cloud."])
    TimersTab.shared.start(.focus)
    defer { TimersTab.shared.stop() }
    let geometry = NotchGeometry.on(screen: NSRect(x: 0, y: 0, width: 1512, height: 982), visible: NSRect(x: 0, y: 0, width: 1512, height: 944),
                                    notchLeft: 656, notchRight: 856, safeTop: 38)
    func render(_ name: String, settle: TimeInterval = 1.2) throws {
        let view = ZStack(alignment: .top) {
            LinearGradient(colors: [Color(white: 0.66), Color(white: 0.48)], startPoint: .top, endPoint: .bottom)
            NotchRootView(hub: hub, geometryOverride: geometry).environment(\.notchFlatGlass, true)
        }
        if let url = try renderOffscreen(view, size: geometry.open.size, name: name, settle: settle) { assertNoBlue(url) }
    }
    hub.stageForPreview(open: true)
    for tab in hub.orderedTabs {
        hub.selectedID = tab.id
        if tab.id == WeatherTab.shared.id {
            MouthyTabs.networkAllowed = { true }
            WeatherTab.shared.showForPreview(place: .init(name: "Paris, France", latitude: 48.9, longitude: 2.3, fahrenheit: true),
                                             now: WeatherTab.sampleNow, days: WeatherTab.sampleDays)
        }
        try render("tab-\(tab.id)")
        MouthyTabs.networkAllowed = { false }
    }
    hub.selectedID = WeatherTab.shared.id
    try render("tab-mouthy.weather-local-only")
    MouthyTabs.networkAllowed = { true }
    WeatherTab.shared.showLoadingForPreview()
    try render("tab-mouthy.weather-loading")
    MouthyTabs.networkAllowed = { false }
    hub.selectedID = VoiceTab.shared.id
    model.phase = .listening
    model.level = 0.6
    model.targetName = "Notes"
    model.elapsed = 7
    model.liveText = "Book the dentist for Thursday at nine and ask whether they can"
    try render("tab-mouthy.voice-listening")
    model.phase = .idle
    model.liveText = ""
    model.status = "Ready to copy. Enable Accessibility for automatic insertion."
    try render("tab-mouthy.voice-attention")
    model.status = "Ready." 
    hub.selectedID = ShortcutsTab.shared.id
    try render("tab-mouthy.shortcuts-now")
    // The loaded grid with one pinned shortcut, then the empty state (storage is the scratch folder above).
    ShortcutsTab.shared.showForPreview(names: ["Focus 25", "Log water", "Make a GIF", "Morning routine", "Resize image", "Send my ETA"])
    ShortcutsTab.shared.pinned = ["Send my ETA"]
    try render("tab-mouthy.shortcuts-loaded")
    ShortcutsTab.shared.showForPreview(names: [])
    try render("tab-mouthy.shortcuts-empty")
    ShortcutsTab.shared.pinned = []
}

/// MOUTHY_RENDER_DIR=<dir>: the peek cards (finished focus, charging, a new song) in the closed notch.
@MainActor @Test func peekCardsRenderForVisualReview() throws {
    guard ProcessInfo.processInfo.environment["MOUTHY_RENDER_DIR"] != nil else { return }
    let original = MouthyTabs.networkAllowed
    MouthyTabs.networkAllowed = { false }
    defer { MouthyTabs.networkAllowed = original }
    MusicTab.shared.lyricsEnabled = false
    MusicTab.shared.update(["Name": "Northern Lights", "Artist": "Mouthy Radio", "Player State": "Playing", "Duration": 180000], player: "Music")
    let cards: [(String, AnyView)] = [("timer", AnyView(TimerDonePeek(kind: .focus, streak: 3))), ("timer-rest", AnyView(TimerDonePeek(kind: .rest, streak: 0))),
                                      ("power", AnyView(PowerPeek(charging: true, percent: 82))), ("battery", AnyView(PowerPeek(charging: false, percent: 14))),
                                      ("track", AnyView(TrackPeek(model: MusicTab.shared, track: MusicTab.shared.track!)))]
    let geometry = NotchGeometry.on(screen: NSRect(x: 0, y: 0, width: 1512, height: 982), visible: NSRect(x: 0, y: 0, width: 1512, height: 944),
                                    notchLeft: 656, notchRight: 856, safeTop: 38)
    Mascot.install()
    let hub = NotchHub()
    for (name, card) in cards {
        hub.stageForPreview(peek: card, title: name)
        let view = ZStack(alignment: .top) {
            LinearGradient(colors: [Color(white: 0.66), Color(white: 0.48)], startPoint: .top, endPoint: .bottom)
            NotchRootView(hub: hub, geometryOverride: geometry).environment(\.notchFlatGlass, true)
        }
        if let url = try renderOffscreen(view, size: CGSize(width: geometry.open.width, height: 150), name: "peek-\(name)", settle: 1.4) { assertNoBlue(url) }
    }
}

/// MOUTHY_RENDER_DIR=<dir>: Settings → Notch hub (tab list with drag handles and switches, hover delay, haptics).
@MainActor @Test func mouthyTabsSettingsRenderForVisualReview() throws {
    guard ProcessInfo.processInfo.environment["MOUTHY_RENDER_DIR"] != nil else { return }
    let view = ZStack {
        MouthyBackdrop()
        Tile { NotchSettingsView() }.padding(24)
    }
    .tint(MouthyTheme.orange)
    if let url = try renderOffscreen(view, size: CGSize(width: 620, height: 640), name: "notch-settings", settle: 0.6) { assertNoBlue(url) }
}

@Test func calendarAsksForBothTogetherOnlyBeforeEither() {
    #expect(CalendarTab.asksTogether(calendar: .notDetermined, reminders: .notDetermined))
    #expect(!CalendarTab.asksTogether(calendar: .fullAccess, reminders: .notDetermined))
    #expect(!CalendarTab.asksTogether(calendar: .denied, reminders: .notDetermined))
    #expect(CalendarTab.privacyURL(reminders: false).absoluteString.hasSuffix("?Privacy_Calendars"))
    #expect(CalendarTab.privacyURL(reminders: true).absoluteString.hasSuffix("?Privacy_Reminders"))
}
