import AppKit
import MouthyNotch
import SwiftUI

/// Recent clipboard text and files, kept in memory only. Passwords and other concealed items are skipped.
@MainActor final class ClipboardTab: ObservableObject, NotchTab {
    static let shared = ClipboardTab()
    struct Item: Identifiable, Equatable {
        let id = UUID()
        let text: String?
        let files: [URL]
        var image: NSImage? = nil
        let app: String?
        let date: Date
        var preview: String {
            if let text { return text.trimmingCharacters(in: .whitespacesAndNewlines).replacingOccurrences(of: "\n", with: " ⏎ ") }
            if let image { return "Image \(Int(image.size.width))×\(Int(image.size.height))" }
            return files.map(\.lastPathComponent).joined(separator: ", ")
        }
    }

    let id = "mouthy.clipboard"
    let title = "Clipboard"
    let symbolName = "doc.on.clipboard"
    @Published private(set) var items: [Item] = []
    @Published var paused = false
    private var lastChange = NSPasteboard.general.changeCount
    private var watcher: Timer?
    private var activationObserver: NSObjectProtocol?
    static let limit = 40
    /// nspasteboard.org markers that password managers and Mouthy's own paste use.
    static let skipped: Set<String> = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                                      "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"]

    private init() {}

    /// How often the pasteboard's change counter is read, and how much the system may shift each check.
    static let pollInterval: TimeInterval = 1.5
    static let pollTolerance: TimeInterval = 1.0

    /// NSPasteboard has no change notification; reading one integer every 1.5 s (with a generous tolerance so
    /// the system can batch wake-ups) is the standard, near-free way. Switching apps checks at once, which
    /// catches a copy made just before.
    func startWatching() {
        guard watcher == nil else { return }
        let timer = Timer(timeInterval: Self.pollInterval, repeats: true) { [weak self] _ in Task { @MainActor in self?.check() } }
        timer.tolerance = Self.pollTolerance
        RunLoop.main.add(timer, forMode: .common)
        watcher = timer
        activationObserver = NSWorkspace.shared.notificationCenter.addObserver(forName: NSWorkspace.didActivateApplicationNotification, object: nil, queue: .main) { [weak self] _ in
            Task { @MainActor in self?.check() }
        }
    }
    func stopWatching() {
        watcher?.invalidate(); watcher = nil
        if let activationObserver { NSWorkspace.shared.notificationCenter.removeObserver(activationObserver) }
        activationObserver = nil
    }

    /// Whether a pasteboard carrying these types is skipped (passwords, one-off and generated content).
    static func shouldSkip(types: Set<String>) -> Bool { !types.isDisjoint(with: skipped) }

    private func check() {
        let board = NSPasteboard.general
        guard board.changeCount != lastChange else { return }
        lastChange = board.changeCount
        guard !paused else { return }
        let types = Set((board.types ?? []).map(\.rawValue))
        guard !Self.shouldSkip(types: types) else { return }
        let files = (board.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL]) ?? []
        let text = files.isEmpty ? board.string(forType: .string) : nil
        // Images only when nothing else was copied; anything over 20 MB is skipped to keep memory bounded.
        var image: NSImage?
        if files.isEmpty, text == nil, let data = board.data(forType: .png) ?? board.data(forType: .tiff), data.count < 20_000_000 {
            image = NSImage(data: data)
        }
        guard (text?.isEmpty == false) || !files.isEmpty || image != nil else { return }
        let item = Item(text: text, files: files, image: image, app: NSWorkspace.shared.frontmostApplication?.localizedName, date: Date())
        if image == nil { items.removeAll { $0.text == item.text && $0.files == item.files && $0.image == nil } }
        if items.filter({ $0.image != nil }).count >= 8, image != nil, let last = items.lastIndex(where: { $0.image != nil }) { items.remove(at: last) }
        items.insert(item, at: 0)
        if items.count > Self.limit { items.removeLast(items.count - Self.limit) }
        NotchHub.shared.tabDidChange(id: id)
    }

    func copy(_ item: Item) {
        let board = NSPasteboard.general
        board.clearContents()
        if let text = item.text { board.setString(text, forType: .string) }
        else if let image = item.image { board.writeObjects([image]) }
        else { board.writeObjects(item.files as [NSURL]) }
        lastChange = board.changeCount
        items.removeAll { $0.id == item.id }
        items.insert(item, at: 0)
        NotchHub.shared.presentResult("Copied", ok: true)
    }

    func clear() { items.removeAll(); NotchHub.shared.tabDidChange(id: id) }

    /// Renders and tests: fills the list with sample text instead of the real pasteboard.
    func showForPreview(_ texts: [String]) {
        items = texts.enumerated().map { Item(text: $1, files: [], app: "Notes", date: Date().addingTimeInterval(-Double($0 * 95 + 20))) }
    }

    func makeBody() -> AnyView { AnyView(ClipboardView(model: self)) }
}

struct ClipboardView: View {
    @ObservedObject var model: ClipboardTab
    @State private var search = ""
    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack(spacing: 10) {
                NotchField(prompt: "Search clipboard", text: $search)
                Toggle("Capture clipboard", isOn: Binding(get: { !model.paused }, set: { model.paused = !$0 }))
                    .toggleStyle(WarmSwitchStyle(mini: true, showsLabel: true))
                    .font(.system(size: 13, weight: .medium)).foregroundStyle(MouthyTheme.cream2)
                    .fixedSize()
                    .help("When off, new copies are not kept")
                PillButton(title: "Clear") { model.clear() }
                    .disabled(model.items.isEmpty)
            }
            let shown = search.isEmpty ? model.items : model.items.filter { $0.preview.localizedCaseInsensitiveContains(search) }
            if shown.isEmpty {
                if model.items.isEmpty {
                    NotchEmptyState(pose: .sleep, title: model.paused ? "Capture is off" : "Nothing copied yet",
                                    message: model.paused ? "Turn on Capture clipboard to keep new copies." : "Copy something and it shows up here. Kept in memory only; passwords are skipped.")
                } else {
                    NotchEmptyState(pose: .sleep, title: "No matches")
                }
            } else {
                ScrollView(showsIndicators: false) {
                    LazyVStack(alignment: .leading, spacing: 1) {
                        ForEach(shown) { item in ClipboardRow(item: item) { model.copy(item) } }
                    }
                }
                .notchScrollFade()
            }
        }
    }
}

struct ClipboardRow: View {
    let item: ClipboardTab.Item
    let copy: () -> Void
    var body: some View {
        Button(action: copy) {
            HStack(spacing: 9) {
                if let image = item.image {
                    Image(nsImage: image).resizable().aspectRatio(contentMode: .fill).frame(width: 18, height: 18)
                        .clipShape(RoundedRectangle(cornerRadius: 4, style: .continuous))
                } else {
                    Image(systemName: item.text == nil ? "doc" : "text.alignleft").font(.system(size: 13))
                        .foregroundStyle(MouthyTheme.glow.opacity(0.85)).frame(width: 18)
                }
                Text(item.preview).font(.system(size: 14)).foregroundStyle(MouthyTheme.cream).lineLimit(1).truncationMode(.tail)
                Spacer(minLength: 8)
                // A steady "2 min ago" in a fixed column, refreshed once a minute, instead of seconds counting up.
                TimelineView(.everyMinute) { context in
                    Text(ClipboardRow.age(item.date, now: context.date))
                        .font(.system(size: 12)).monospacedDigit().foregroundStyle(MouthyTheme.cream2).lineLimit(1)
                        .frame(width: 64, alignment: .trailing)
                }
            }
            .padding(.vertical, 5)
            .contentShape(Rectangle())
            .hoverRow()
        }
        .buttonStyle(.plain)
        .help(item.app.map { "From \($0). Click to copy." } ?? "Click to copy.")
    }

    /// "now" under a minute, then "2 min ago", "3 hr ago", "2 days ago".
    static func age(_ date: Date, now: Date) -> String {
        guard now.timeIntervalSince(date) >= 60 else { return "now" }
        return date.formatted(.relative(presentation: .numeric, unitsStyle: .abbreviated)).replacingOccurrences(of: ".", with: "")
    }
}
